# Generated by Django 5.2.17 on 2026-08-31 19:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Box name or model code', max_length=120)),
                ('inner_length', models.DecimalField(decimal_places=2, help_text='Usable inner length in centimeters (cm)', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('inner_width', models.DecimalField(decimal_places=2, help_text='Usable inner width in centimeters (cm)', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('inner_height', models.DecimalField(decimal_places=2, help_text='Usable inner height in centimeters (cm)', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('max_weight', models.DecimalField(decimal_places=2, help_text='Maximum weight capacity in grams (g)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cost', models.DecimalField(decimal_places=2, help_text='Cost per box in standard currency units', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'verbose_name': 'Shipping Box',
                'verbose_name_plural': 'Shipping Boxes',
                'ordering': ['cost', 'inner_length'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('boxed', 'Boxed'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name/title', max_length=120)),
                ('sku', models.CharField(help_text='Unique Stock Keeping Unit', max_length=64, unique=True)),
                ('length', models.DecimalField(decimal_places=2, help_text='Length in centimeters (cm)', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('width', models.DecimalField(decimal_places=2, help_text='Width in centimeters (cm)', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in centimeters (cm)', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in grams (g)', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of this product', validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipping.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='shipping.product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['id'],
            },
        ),
    ]
